name: Run ip-cf.py

on:
  schedule:
    - cron: '0 */10 * * *' # 每10小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 更新到 v3

    - name: Set up Python
      uses: actions/setup-python@v4  # 更新到 v4
      with:
        python-version: '3.x'  # 替换为所需的Python版本，例如 '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run baipiao.py
      run: |
        python baipiao.py
        sleep 5  # 暂停5秒钟
      continue-on-error: true
        
    - name: Run cf-gf.py
      run: |
        python cf-gf.py
        sleep 5  # 暂停5秒钟
      continue-on-error: true

    - name: Run cf-fd.py
      run: |
        python cf-fd.py
        sleep 5  # 暂停5秒钟
      continue-on-error: true

    - name: Run ip-cf.py
      run: |
        python ip-cf.py
      env:
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_SUBDOMAIN: ${{ secrets.CF_SUBDOMAIN }}
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
    - name: Clean up temporary files
      run: |
        rm -rf result.csv ，cf-gf.csv ，cf-fd.csv
