name: Cleaning up logs

on:
  schedule:
    # 每三天运行一次
    #- cron: '0 0 */3 * *'

  # 添加手动触发
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 设置 GitHub CLI
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      # 步骤 2: 清理旧的运行记录
      - name: Delete old workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.YZ_TOKEN }}
        run: |
          # 获取需要删除的运行记录 ID
          runs=$(gh api repos/${{ github.repository }}/actions/runs --paginate --jq '.workflow_runs[] | select(.status == "completed" and .created_at < ((now - 259200) | strftime("%Y-%m-%dT%H:%M:%SZ"))) | .id')

          # 删除运行记录
          for run_id in $runs; do
            gh api --method DELETE repos/${{ github.repository }}/actions/runs/$run_id
            echo "Deleted run $run_id"
          done

      # 步骤 3: 清理缓存
      - name: Clear GitHub Actions cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-
        if: always() # 即使前面的步骤失败也会执行

      # 步骤 4: 打印清理完成信息
      - name: Print cleanup completion
        run: echo "Cleanup completed successfully!"
