name: Download IP Addresses

on:
  workflow_dispatch:

jobs:
  download_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Download IP file
        run: curl -o ip.txt https://ipdb.api.030101.xyz/?type=cfv4\;proxy\&down=true

      - name: Add downloaded file to Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ip.txt
          git commit -m "Add ip.txt file"
