name: Download IP Addresses

on:
  workflow_dispatch:

jobs:
  download_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download IP file
        run: curl -o ip.txt https://ipdb.api.030101.xyz/?type=cfv4\;proxy\&down=true

      - name: Read downloaded file and write content to ip.txt
        run: |
          content=$(cat ip.txt)
          echo "$content" > ./ip.txt

      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git add ip.txt
          git commit -m "Update ip.txt file"
          git push https://github.com/yuanzhou029/ip.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
