name: Download IP Addresses

on:
  schedule:
    - cron:  '30 21 * * *'  #北京时间5:30分
  workflow_dispatch:  
jobs:
  download_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 设置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 安装GitPython库
        run: pip install gitpython

      - name: 安装requests库
        run: pip install requests

      - name: 安装GeoIP2库
        run: pip install geoip2
        
      - name: Download IP file
        run: curl -o ip.txt https://ipdb.api.030101.xyz/?type=cfv4\;proxy\&down=true

      - name: Read downloaded file and write content to ip.txt
        run: |
          content=$(cat ip.txt)
          echo "$content" > ./ip.txt

      - name: 运行Python脚本
        run: python query_japan_ips.py
