name: Fetch and Filter IPs

on:
  workflow_dispatch:

jobs:
  fetch_and_filter_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch IP addresses
        run: |
          ips=$(curl -s "https://ipdb.api.030101.xyz/?type=cfv4;proxy&down=true")

          # Filter IPs by country (Japan, Korea, Singapore, Hong Kong, Taiwan)
          filtered_ips=$(echo "$ips" | jq -r '. | select(.country_code | contains("JP", "KR", "SG", "HK", "TW")) | .ip')

          # Save filtered IPs to 123.txt file
          echo "$filtered_ips" > 123.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add 123.txt
          git commit -m "Update IP addresses"
          git push
