name: Download IP Addresses

on:
  workflow_dispatch:

jobs:
  download_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download IP addresses
        run: curl -o ip_list.txt "https://ipdb.api.030101.xyz/?type=cfv4;proxy&down=true"

      - name: Commit and push changes
        if: success() # 仅在前面的步骤成功后执行
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ip_list.txt
          git commit -m "Update IP addresses"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:main
