name: Download IP Addresses

on:
  workflow_dispatch:

jobs:
  download_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Run Python script to download IP addresses
        run: python download_ip.py

      - name: Set git user
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git add ip.txt
          git commit -m "Update IP addresses"
          git push https://github.com/${{ github.repository }} HEAD:main
          # 使用个人访问令牌进行推送
          # git push https://github.com/${{ secrets.REPO_NAME }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
