name: Download IP Addresses

on:
  workflow_dispatch:

jobs:
  download_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Print current working directory
        run: pwd
        id: print_pwd

      - name: Run Python script to download IP addresses
        run: python ${{ steps.print_pwd.outputs.stdout }}/download_ip.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ip.txt
          git commit -m "Update IP addresses"
          git push
