name: 查询日本IP
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 每天5点运行, 时区+8
jobs:
  query_ips:
    runs-on: ubuntu-latest

    steps:
      - name: 检出存储库
        uses: actions/checkout@v2

      - name: 设置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装GitPython库
        run: pip install gitpython

      - name: 安装requests库
        run: pip install requests

      - name: 安装GeoIP2库
        run: pip install geoip2

      - name: 运行Python脚本
        run: python query_japan_ips.py
