ame: Download IP Addresses

on:
  schedule:
    - cron:  '30 21 * * *'  #北京时间5:30分
  workflow_dispatch: # 添加手动触发器

jobs:
  download_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download ZIP file
        uses: actions/download-artifact@v3
        with:
          url: https://zip.baipiao.eu.org
          path: downloaded_zip.zip

      - name: Unzip file
        uses: actions/extract/zip@v3
        with:
          path: downloaded_zip.zip

      - name: Merge TXT files
        run: |
          find . -name "*.txt" -exec cat {} \; > ip.txt
          cat ip.txt     

      - name: Read downloaded file and write content to ip.txt
        run: |
          cat ip.txt > ./ip.txt

      - name: Commit and push changes
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ip.txt
          git commit -m 'Update IP addresses'
          git push
